CREATE DATABASE AIRLINE;
USE AIRLINE;

CREATE TABLE FOLLOWS (
    FOLLOWING_USER_ID INT,
    FOLLOWED_USER_ID INT,
    CREATED_AT TIMESTAMP
);
INSERT INTO FOLLOWS (FOLLOWING_USER_ID, FOLLOWED_USER_ID, CREATED_AT)
VALUES (1, 34, '2023-10-04 09:58:59');
SELECT * FROM FOLLOWS;


CREATE TABLE PASSENGER (
    PASSENGER_ID INT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PASSPORT_NUMBER VARCHAR(100)
);
INSERT INTO PASSENGER (PASSENGER_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSPORT_NUMBER)
VALUES (67, 'SHRAVANI', 'SHEDGE', 'shravani@gmail.com', '57389');
SELECT * FROM PASSENGER;


CREATE TABLE PAYMENT (
    PAYMENT_ID INT,
    BOOKING_ID INT,
    PAYMENT_METHOD VARCHAR(100),
    AMOUNT DECIMAL(10,2),
    TRANSACTION_DATE_TIME DATETIME
);

INSERT INTO PAYMENT ()
VALUES (23, 42109,'ONLINE', 12000.00, '2003-04-11 08:50:23');

SELECT * FROM PAYMENT;


CREATE TABLE USERS(
ID INT,
USERNAME VARCHAR(200),
ROLE VARCHAR(200),
CREATED_AT TIMESTAMP);
INSERT INTO USERS(ID,USERNAME,ROLE,CREATED_AT)
VALUES(21,"SHRAVANI SHEDGE","PASSENGER",'2003-04-11 08:50:23');
SELECT * FROM USERS;

CREATE TABLE AIRPORT(
AIRPORT_CODE VARCHAR(200),
AIRPORT_NAME VARCHAR(200),
LOCATION VARCHAR(200),
FACILTIES VARCHAR(200));
INSERT INTO AIRPORT(AIRPORT_CODE,AIRPORT_NAME,LOCATION,FACILTIES)
VALUES("7838","MOPA AIRPORT","GOA","NA");
SELECT * FROM AIRPORT;inventory

CREATE TABLE POSTS(
ID INT,
TITLE VARCHAR(200),
BODY TEXT,
USER_ID INT,
STATUS VARCHAR(200),
CREATED_AT TIMESTAMP);
INSERT INTO POSTS()
VALUES(56,"NA","NA",8965,"YES",'2003-04-11 08:50:23');
SELECT * FROM POSTS;

CREATE TABLE AIRLINE(
AIRLINE_ID INT,
AIRLINE_NAME VARCHAR(100),
CONTACT_NUMBER VARCHAR(100),
OPERATING_REGION VARCHAR(100));
INSERT INTO AIRLINE(AIRLINE_ID,AIRLINE_NAME,CONTACT_NUMBER,OPERATING_REGION)
VALUES(67288,"MUMBAI AIRPORT","8805398664","MUMBAI");
SELECT * FROM AIRLINE;

CREATE TABLE FLIGHT(
FLIGHT_ID INT,
FLIGHT_NUMBER VARCHAR(200),
DEPARTURE_DATETIME DATETIME,
ARRIVE_DATETIME DATETIME,
ORIGINAL_AIRPORTCODE VARCHAR(200),
DESIGNATION_AIRPORTCODE VARCHAR(200),
AVAILABLE_SEATS INT);
INSERT  INTO FLIGHT()
VALUES(101,"37923871",'2003-04-11 08:50:23',"2003-04-11 08:50:23","NA","NA",56);
SELECT * FROM FLIGHT;

CREATE TABLE BOOKING(
BOOKING_ID INT,
FLIGHT_ID INT,
PASSENGER_ID INT,
PAYMENT_STATUS VARCHAR(200));
INSERT INTO BOOKING(BOOKING_ID,FLIGHT_ID,PASSENGER_ID,PAYMENT_STATUS)
VALUES(78264,29727,784827,"NA");
SELECT*FROM BOOKING;

