CREATE DATABASE BLOB_EG;
USE BLOB_EG;

CREATE TABLE IMAGES(
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
IMAGE_DATA LONGBLOB NOT NULL);



SELECT @@secure_file_priv;
INSERT INTO IMAGES (TITLE, IMAGE_DATA) 
VALUES("MY LOGO", LOAD_FILE("C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/MYSQL.png"));

select * from images;