create database sales;
use sales;

CREATE TABLE USERS(
USER_ID INT PRIMARY KEY,
EMAIL VARCHAR(50),
NAME VARCHAR(50));


INSERT INTO USERS(USER_ID,EMAIL,NAME)
VALUES(10,"sadio1@example.com","sadio"),
(11,"mo@example.com","sadio"),
(12,"rinsola@example.com","Rinsola"),
(13,"amalie@example.com","Amalie");

SELECT * FROM USERS;

CREATE TABLE ORDERS(
ORDER_NO INT ,
PRODUCT_SKU INT PRIMARY KEY,
USER_ID INT NOT NULL references USERS(USER_ID));

INSERT INTO ORDERS()
VALUES(93,11,123),
(94,11,789),
(95,13,789),
(96,10,101);

SELECT * FROM ORDERS;

CREATE TABLE BOOKS(
PRODUCT_SKU INT NOT NULL references ORDERS(PRODUCT_SKU),
TITLE VARCHAR(50),
PRICE INT);


INSERT INTO BOOKS(PRODUCT_SKU,TITLE,PRICE)
VALUES(123,"AURORA",15),
(456,"BLIND LAKE",10),
(789,"INVISIBLE PLANETS",25),
(101,"THE SPARROW",15);

SELECT * FROM BOOKS;














