USE EXTERNAL_PRACTICAL;

CREATE TABLE CUSTOMER(
ID INT,
NAME VARCHAR(20),
AGE INT,
ADDRESS VARCHAR(20),
SALARY INT);

DROP TABLE CUSTOMER;

INSERT INTO CUSTOMER()
VALUES(1,"RAM",35,"DANOLI",3000),
(2,"SHAM",32,"SHIROLI",3000),
(3,"RAMESH",38,"VENGURLA",3000),
(4,"SEETA",30,"VASOLI",3000);

SELECT * FROM CUSTOMER;

-- PROCEDURE
DELIMITER //

CREATE PROCEDURE TEST()

BEGIN
UPDATE CUSTOMER SET SALARY = 366000 WHERE ADDRESS = "DANOLI";
END//

DELIMITER ;
SET SQL_SAFE_UPDATES = 0;
CALL TEST();

