CREATE DATABASE SMALL_BUSINESS ;
USE SMALL_BUSINESS;

CREATE TABLE CUSTOMER(
CUSTOMERID INT,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(20),
EMAIL_ID VARCHAR(30),
PHONE_NUMBER varchar(30),
DELIVERY_ADDRESS VARCHAR(100));


INSERT INTO CUSTOMER(CUSTOMERID,FIRST_NAME,LAST_NAME,EMAIL_ID,PHONE_NUMBER,DELIVERY_ADDRESS)
VALUES(1,"SHRAVANI","SHEDGE","shravani1@gmail.com","8805398664","sindhudurg kudal");
SELECT * FROM CUSTOMER;

CREATE TABLE PAYMENT(
TRANSACTION_ID INT,
PAYMENT_MODE VARCHAR(30),
AMOUNT NUMERIC(5,2),
TAXES NUMERIC(3,2),
TOTAL_AMOUNT NUMERIC(5,2),
STATUS VARCHAR(10));

INSERT INTO PAYMENT(TRANSACTION_ID,PAYMENT_MODE,AMOUNT,TAXES,TOTAL_AMOUNT,STATUS)
VALUES(123,"ONLINE",120.56,3.52,450.4,"DELIVERED");

SELECT * FROM PAYMENT;

CREATE TABLE RATING(
RATING_ID INT,
CUSTOMER_ID INT,
RESTAURANT_ID INT,
RATING INT);

INSERT INTO RATING(RATING_ID,CUSTOMER_ID,RESTAURANT_ID,RATING)
VALUES(124,6745,345675,5);
SELECT * FROM RATING;

CREATE TABLE ORDERS(
ORDER_ID INT,
CUSTOMER_ID INT,
RESTUARANT_ID INT,
FOOD_ID INT,
FOODITEM VARCHAR(20),
TRANSACTION_ID VARCHAR(30),
TOTAL_AMOUNT NUMERIC(5,2),
DELIVERY_PERSONID NUMERIC(5,2),
STATUS VARCHAR(10));

INSERT INTO ORDERS()
VALUES(12456,2342,23445,2,"PIZAA","S98",450.87,90,"DELIVERED");
SELECT * FROM ORDERS;

CREATE TABLE DELIVERY_PERSON(
DELIVERYPERSONG_ID INT,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(20),
EMAIL_ID VARCHAR(30),
PHONE_NUMBER VARCHAR(200));


INSERT INTO DELIVERY_PERSON(DELIVERYPERSONG_ID,FIRST_NAME,LAST_NAME,EMAIL_ID,PHONE_NUMBER)
VALUES(123,"SHRIYA","PALKAR","shriya1@gmail.com","8938298365");
SELECT * FROM DELIVERY_PERSON;

CREATE TABLE RESTUARANT(
RESTAURANT_ID INT,
RESTUARANT_NAME VARCHAR(30),
MENU_ID INT,
EMAIL_ID VARCHAR(30),
PHONE_NUMBER VARCHAR(20),
ADDRESS VARCHAR(100),
RATING INT
);
DROP TABLE RESTUARANT;

INSERT INTO RESTUARANT(RESTAURANT_ID,RESTUARANT_NAME,MENU_ID,EMAIL_ID,PHONE_NUMBER,ADDRESS,RATING)
VALUES(1553,"GAJALI HOTEL",34,"gajalihotel@gmail.com","3673840904","VENGURLA",4restuarant);
SELECT * FROM RESTUARANT;

CREATE TABLE MENU(
MENU_ID INT,
FOODITEM VARCHAR(30),
CATEGORY_ID INT,
PRICE NUMERIC(4,2),
QUALITY INT);

INSERT INTO MENU(MENU_ID,FOODITEM,CATEGORY_ID,PRICE,QUALITY)
VALUES(23,"BURGER",45,34.4,10);
SELECT * FROM MENU;


CREATE TABLE CATEGORY(
CATEGORY_ID INT,
CATEGORY_NAME VARCHAR(20),
ISVEG VARCHAR(3),
ISNONVEG VARCHAR(3));

INSERT INTO CATEGORY(CATEGORY_ID,CATEGORY_NAME,ISVEG,ISNONVEG)
VALUES(234,"CHINESS","NO","YES");

SELECT * FROM CATEGORY;



