USE EXTERNAL_PRACTICAL;
CREATE TABLE EMPLOYEE(
ID int,
salary int
);

drop table BACKUP;
insert into EMPLOYEE()
values(1,5666),
(2,5666666);

select * from EMPLOYEE;
CREATE TABLE BACKUP(
ID int,
salary int);

delimiter //
CREATE TRIGGER T1
BEFORE DELETE
ON EMPLOYEE
FOR EACH ROW
BEGIN
INSERT INTO BACKUP VALUES(old.ID,old.salary);
END; // 

SET SQL_SAFE_UPDATES = 0;

DELETE FROM EMPLOYEE WHERE ID = 1;  
SELECT * FROM BACKUP;