CREATE DATABASE TASK_PRIFOR;
USE TASK_PRIFOR;

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
EMP_NAME VARCHAR(200),
EMP_AGE INT,
EMP_ADD VARCHAR(200));

INSERT INTO EMPLOYEE(ID,EMP_NAME,EMP_AGE,EMP_ADD)
VALUES(1,"shravani",21,"sindhudurg"),
(2,"shriya",23,"sindhudurg"),
(3,"manu",21,"satara"),
(4,"revati",23,"kolhapur"),
(5,"barki",24,"sangli");

SELECT * FROM EMPLOYEE;
DROP TABLE EMP_INFO;

CREATE TABLE EMP_INFO(
    SALARY INT,
    DEP VARCHAR(200),
    ID INT NOT NULL REFERENCES EMPLOYEE (ID)
);

INSERT INTO EMP_INFO(SALARY,DEP,ID)
VALUES(23000,"ML",1),
(56000,"AI",2),
(234000,"HR",3),
(120000,"DL",4),
(450000,"ML",5);

SELECT * FROM EMP_INFO;

