CREATE DATABASE TASK9;
USE TASK9;

CREATE TABLE STUDENT(
ID INT ,
AGE INT,
NAME VARCHAR(60),
BRANCH VARCHAR(60)
);

INSERT INTO STUDENT(ID,AGE,NAME,BRANCH)
VALUES(1,21,"shravani shedge","computer science"),
(2,23,"priya patil","data science"),
(3,21,"shriya palkar","computer science"),
(4,22,"mrunal salunkhe","data science"),
(5,21,"revati ingavale","data science"),
(6,23,"ajinkya dhere","MBA");

SELECT * FROM STUDENT;

CREATE TABLE STD_INFO(
ID INT,
NAME VARCHAR(100),
ADDRESS VARCHAR(50)
);

INSERT INTO STD_INFO(ID,NAME,ADDRESS)
VALUES(1,"shreya ","kokan"),
(2,"mayuri","kolhapur"),
(3,"shriya","sindhudurg"),
(5,"revati","kokan");

SELECT * FROM STD_INFO;

-- JOINS --
-- INNER JOIN --
SELECT * FROM STUDENT
INNER JOIN
STD_INFO ON STUDENT.ID = STD_INFO.ID;

-- CROSS JOIN
SELECT * FROM STUDENT
CROSS JOIN
STD_INFO ON STUDENT.ID = STD_INFO.ID;

-- LEFT JOIN
SELECT * FROM STUDENT
LEFT JOIN
STD_INFO ON STUDENT.ID = STD_INFO.ID;

-- RIGHT JOIN 
SELECT * FROM STUDENT
RIGHT JOIN
STD_INFO ON STUDENT.ID = STD_INFO.ID;

-- FULL JOIN
SELECT * FROM STUDENT 
FULL JOIN STD_INFO ON STUDENT.NAME= STD_INFO.NAME;

-- DELETE JOIN
DELETE STUDENT
FROM STUDENT JOIN STD_INFO
WHERE STUDENT.ID = STD_INFO.ID;

